openapi: 3.0.3
info:
  title: Self Assessment Accounts (MTD)
  version: "2.0"
  description: List and retrieve details of Self Assessment balances, transactions, charges and payments.

servers:
  - url: https://test-api.service.hmrc.gov.uk
    description: Sandbox
  - url: https://api.service.hmrc.gov.uk
    description: Production

components:
  securitySchemes:
    User-Restricted:
      type: oauth2
      description: HMRC supports OAuth 2.0 for authenticating [User-restricted](https://developer.qa.tax.service.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints) API requests
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            write:self-assessment: Grant write access
            read:self-assessment: Grant read access

paths:
  /accounts/self-assessment/{nino}/charges/{transactionId}:
    $ref: "./retrieveSelfAssessmentChargeHistory.yaml"
  /accounts/self-assessment/{nino}/balance-and-transactions:
    $ref: "./retrieveSelfAssessmentBalanceAndTransactions.yaml"
  /accounts/self-assessment/{nino}/payments-and-allocations:
    $ref: "./listSelfAssessmentPaymentsAndAllocationDetails.yaml"
  /accounts/self-assessment/{nino}/{taxYear}/collection/tax-code:
    $ref: "./codingunderpayments.yaml"
