openapi: 3.0.0
summary: Delete Coding Out Underpayments and Debt Amounts
description: This endpoint enables you to delete custom coding out amounts for a given tax year and National Insurance number.
security:
  - User-Restricted:
      - write:self-assessment

responses:
  204:
    headers:
      X-CorrelationId:
        $ref: "./common/headers.yaml#/components/parameters/correlationId"

  400:
    description: Bad request
    content:
      application/json:
        examples:
          FORMAT_NINO:
            $ref: "./common/errors.yaml#/components/examples/formatNino"
          FORMAT_TAX_YEAR:
            $ref: "./common/errors.yaml#/components/examples/formatTaxYear"
          RULE_TAX_YEAR_NOT_SUPPORTED:
            $ref: "./common/errors.yaml#/components/examples/ruleTaxYearNotSupported"
          RULE_TAX_YEAR_RANGE_INVALID:
            $ref: "./common/errors.yaml#/components/examples/ruleTaxYearRangeInvalid"

  403:
    description: Forbidden
    content:
      application/json:
        examples:
          CLIENT_OR_AGENT_NOT_AUTHORISED:
            $ref: "./common/errors.yaml#/components/examples/clientOrAgentNotAuthorised"

  404:
    description: Not found
    content:
      application/json:
        examples:
          CODING_OUT_NOT_FOUND:
            $ref: "./common/errors.yaml#/components/examples/codingOutNotFound"
