is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatTaxYear
  - errors.ruleTaxYearNotSupported
  - errors.ruleTaxYearRangeInvalid
  - errors.clientOrAgentNotAuthorised
  - errors.codingOutNotFound
displayName: "Delete Coding Out underpayments and debt amounts"
description: This endpoint allows the developer to delete custom coding out amounts for a given tax year and NINO.
(annotations.sandboxData): !include scenarios/deleteCodingOutUnderpayments.md
(annotations.scope): "write:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
responses:
  204:
    headers:
      X-CorrelationId:
        example: a1e8057e-fbbc-47a8-a8b4-78d9f015c253
        description: Unique ID for operation tracking <br> String, 36 characters.