openapi: 3.0.0
summary: "List Self Assessment Payments & Allocation Details"
description: This endpoint enables you to list the payments and allocation details of one or more liabilities for a National insurance number.

security:
  - User-Restricted:
      - read:self-assessment

parameters:
  - $ref: "./common/headers.yaml#/components/parameters/acceptJson"
  - $ref: "./common/headers.yaml#/components/parameters/contentTypeJson"
  - $ref: "./common/headers.yaml#/components/parameters/testScenarioHeader"
  - $ref: "./common/queryParameters.yaml#/components/parameters/fromDate"
  - $ref: "./common/queryParameters.yaml#/components/parameters/toDate"
  - $ref: "./common/queryParameters.yaml#/components/parameters/paymentLot"
  - $ref: "./common/queryParameters.yaml#/components/parameters/paymentLotItem"

responses:
  200:
    content:
      application/json:
      schema:
        $ref: "schemas/list_self_assessment_payments_and_allocation_details_schema.json"
      examples:
        Request:
          value:
            $ref: "examples/listSelfAssessmentPaymentsAndAllocationDetails/listSelfAssessmentPaymentsAndAllocationDetails.json"
    headers:
      X-CorrelationId:
        $ref: "./common/headers.yaml#/components/parameters/correlationId"

  400:
    description: Bad request

    content:
      application/json:
        examples:
          FORMAT_NINO:
            $ref: "./common/errors.yaml#/components/examples/formatNino"
          FORMAT_FROM_DATE:
            $ref: "./common/errors.yaml#/components/examples/formatFromDate"
          FORMAT_TO_DATE:
            $ref: "./common/errors.yaml#/components/examples/formatToDate"
          RANGE_TO_DATE_BEFORE_FROM_DATE:
            $ref: "./common/errors.yaml#/components/examples/rangeToDateBeforeFromDate"
          INVALID_DATE_RANGE:
            $ref: "./common/errors.yaml#/components/examples/invalidDateRange"
          MISSING_TO_DATE:
            $ref: "./common/errors.yaml#/components/examples/missingToDate"
          MISSING_FROM_DATE:
            $ref: "./common/errors.yaml#/components/examples/missingFromDate"
          RULE_INCONSISTENT_QUERY_PARAMS_LIST_SA:
            $ref: "./common/errors.yaml#/components/examples/ruleInconsistentQueryParamsListSA"
          FORMAT_PAYMENT_LOT:
            $ref: "./common/errors.yaml#/components/examples/formatPaymentLot"
          FORMAT_PAYMENT_LOT_ITEM:
            $ref: "./common/errors.yaml#/components/examples/formatPaymentLotItem"
          MISSING_PAYMENT_LOT:
            $ref: "./common/errors.yaml#/components/examples/missingPaymentLot"
          MISSING_PAYMENT_LOT_ITEM:
            $ref: "./common/errors.yaml#/components/examples/missingPaymentLotItem"

  403:
    description: Forbidden

    content:
      application/json:
        examples:
          CLIENT_OR_AGENT_NOT_AUTHORISED:
            $ref: "./common/errors.yaml#/components/examples/clientOrAgentNotAuthorised"

  404:
    description: Not found

    content:
      application/json:
        examples:
          NOT_FOUND:
            $ref: "./common/errors.yaml#/components/examples/notFound"
