is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - errors.formatNino
#  - errors.formatStartDate
#  - errors.formatEndDate
#  - errors.ruleEndDateBeforeStartDate
  - errors.invalidDateRange
  - errors.missingToDate
  - errors.missingFromDate
  - errors.clientOrAgentNotAuthorised
  - errors.notFound
  - errors.formatPaymentLot
  - errors.formatPaymentLotItem
displayName: "List Self Assessment Payments & Allocation Details [test only]"
description: This endpoint enables you to list the payments and allocation details of one or more liabilities. A National Insurance number, start date and end date must be provided.
(annotations.sandboxData): !include scenarios/default.md
(annotations.scope): "read:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
queryParameters:
  from:
    description: "The start date of the period to filter payments."
    type: string
    example: "2019-01-02"
    required: true
  to:
    description: "The end date of the period to filter payments."
    type: string
    example: "2020-01-02"
    required: true
  paymentLot:
    description: "An identifier for the batch process that processed the payment and assigned it to the taxpayer's account."
    type: string
    example: "081203010024"
    required: false
  paymentLotItem:
    description: "An identifier for each payment within a payment lot. paymentLot and paymentLotItem together uniquely identify a payment."
    type: string
    example: "000001"
    required: false
responses:
  200:
    body:
      type: !include schemas/list_self_assessment_payments_and_allocation_details_schema.json
      examples:
        example-1:
          description:
          value: !include examples/listSelfAssessmentPaymentsAndAllocationDetails/listSelfAssessmentPaymentsAndAllocationDetails.json
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.