is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.clientOrAgentNotAuthorised
  - errors.formatTransactionId
  - errors.notFound
displayName: "Retrieve Self Assessment Balance and Transactions [test only]"
description: This endpoint enables you to retrieve the overall liability broken down into overdue, currently due (payable), and pending (not yet due) amounts. A National Insurance number must be provided.
(annotations.sandboxData): !include scenarios/default.md
(annotations.scope): "read:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
responses:
  200:
    body:
      type: !include schemas/retrieve_self_assessment_charge_history_response.json
      examples:
        example-1:
          description:
          value: !include examples/retrieveSelfAssementChargeHistory/retrieve_response.json
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.