is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.invalidDocNumber
  - errors.invalidOnlyOpenItems
  - errors.invalidIncludeLocks
  - errors.invalidCalculateAccruedInterest
  - errors.invalidCustomerPaymentInformation
  - errors.invalidDateFrom
  - errors.invalidDateTo
  - errors.invalidRemovePaymentOnAccount
  - errors.invalidIncludeChargeEstimate
  - errors.invalidDateRange
  - errors.ruleInconsistentQueryParams
  - errors.clientOrAgentNotAuthorised
displayName: "Retrieve Self Assessment Balance and Transactions [test only]"
description: This endpoint enables you to retrieve the overall liability broken down into overdue, currently due (payable), and pending (not yet due) amounts. A National Insurance number must be provided.
(annotations.sandboxData): !include scenarios/retrieveSelfAssessmentBalanceAndTransactions.md
(annotations.scope): "read:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
responses:
  200:
    body:
      type: !include schemas/retrieveBalanceAndTransactions.json
#      examples:
#        example-1:
#          description:
#          value: !include examples/retrieveBalanceAndTransactions/retrieveBalanceAndTransactionsFullResponse.json

    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.