#%RAML 1.0
---
title: Self Assessment Accounts (MTD)
description: List and retrieve details of Self Assessment balances, transactions, charges and payments.
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include docs/errors.md
 - title: Changelog
   content: !include docs/changelog.md
 - title: Support
   content: !include docs/support.md
 - title: Testing
   content: !include docs/testing.md

mediaType: application/json

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml
  errors: errors.raml
  headers: headers.raml
  queryParameters: queryParameters.raml

'/accounts/self-assessment':
  /{nino}:
    uriParameters:
      nino:
        description: National Insurance number, in the format AA999999A.
        type: string
        example: TC663795B
    /balance:
      get: !include retrieveBalance.raml
    /transactions:
      get: !include listTransactions.raml
      /{transactionId}:
        uriParameters:
          transactionId:
            description: "A unique identifier for the transaction. <br><br>  Must conform to the regular expression <br/> `^[0-9A-Za-z]{1,12}$`"
            type: string
            example: X92AM39DLE3D
        get: !include retrieveTransactionDetails.raml
    /charges:
      get: !include listCharges.raml
      /{transactionId}:
        uriParameters:
          transactionId:
            description: "A unique identifier for the charge. <br><br>  Must conform to the regular expression <br/> `^[0-9A-Za-z]{1,12}$`"
            type: string
            example: A3948472839A
        get: !include retrieveChargeHistory.raml
    /payments:
      get: !include listPayments.raml
      /{paymentId}:
        uriParameters:
          paymentId:
            description: 'A unique identifier for the payment.<br><br>Must conform to the regular expression: `^[0-9A-Za-z]{1,12}-[0-9A-Za-z]{1,6}$`'
            type: string
            example: "X234567891BY-AT3456"
        get: !include retrieveAllocations.raml
