#%RAML 1.0
---
title: Self Assessment Accounts (MTD)
description: List and retrieve details of Self Assessment balances, transactions, charges and payments.
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Send fraud prevention data
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/fraud-prevention.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include docs/errors.md
 - title: Changelog
   content: !include docs/changelog.md
 - title: Support
   content: !include docs/support.md
 - title: Testing
   content: !include docs/testing.md

mediaType: application/json

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml
  errors: errors.raml
  headers: headers.raml
  queryParameters: queryParameters.raml

'/accounts/self-assessment':
  /{nino}:
    (annotations.group):
      name: Payments and Liabilities
      description: These endpoints allow a developer to retrieve accounting information to be shown back to the customer. This includes listing payments the customer has made, how these payments have been allocated and details of any upcoming or outstanding liabilities. The data returned only relates to payments and liabilities arising for tax years since the customer joined the new service. There may also be outstanding liabilities and payment information a customer needs to view for the years prior to signing up to Making Tax Digital for Income Tax Self Assessment that can be viewed using their existing Personal Tax Account.
    uriParameters:
      nino:
        description: National Insurance number, in the format AA999999A.
        type: string
        example: TC663795B
    /balance:
      get: !include retrieveBalance.raml
    /transactions:
      get: !include listTransactions.raml
      /{transactionId}:
        uriParameters:
          transactionId:
            description: "A unique identifier for the transaction. <br><br>  Must conform to the regular expression <br/> `^[0-9A-Za-z]{1,12}$`"
            type: string
            example: X92AM39DLE3D
        get: !include retrieveTransactionDetails.raml
    /charges:
      get: !include listCharges.raml
      /{transactionId}:
        uriParameters:
          transactionId:
            description: "A unique identifier for the charge. <br><br>  Must conform to the regular expression <br/> `^[0-9A-Za-z]{1,12}$`"
            type: string
            example: A3948472839A
        get: !include retrieveChargeHistory.raml
    /payments:
      get: !include listPayments.raml
      /{paymentId}:
        uriParameters:
          paymentId:
            description: 'A unique identifier for the payment.<br><br>Must conform to the regular expression: `^[0-9A-Za-z]{1,12}-[0-9A-Za-z]{1,6}$`'
            type: string
            example: "X234567891BY-AT3456"
        get: !include retrieveAllocations.raml
    /{taxYear}:
      uriParameters:
        taxYear:
          description: "The tax year the data applies to, for example, 2021-22. The start year and end year must not span two tax years. The minimum tax year is 2021-22. No gaps are allowed, for example, 2020-22 is not valid. (The minimum tax year in Sandbox is 2019-20.). Must conform to the regular expression: `^2[0-9]{3}-[0-9]{2}$`"
          type: string
          example: 2021-22
      /collection:
        (annotations.group):
          name: Coding Out Underpayments and Debts
          description: "Coding out is a concept used to retrieve underpaid tax and debts through a taxpayers PAYE tax code.<br><br> The coding out underpayments and debts endpoints allow software packages to overwrite coding out underpayment and debt amounts that are held by HMRC for a previous tax year and given NINO. Software packages can then amend previously submitted overwrite amounts, retrieve the HMRC held or user submitted coding out amounts or delete the user submitted amounts."
        /tax-code:
          get: !include retrieveCodingOutUnderpayments.raml
          put: !include createOrAmendCodingOutUnderpayments.raml
          delete: !include deleteCodingOutUnderpayments.raml