is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatFromDate
  - errors.formatToDate
  - errors.missingFromDate
  - errors.missingToDate
  - errors.rangeToDateBeforeFromDate
  - errors.ruleDateRangeInvalid
  - errors.ruleFromDateNotSupported
  - errors.clientOrAgentNotAuthorised
  - errors.notFound
  - queryParameters.fromPayments
  - queryParameters.toPayments
displayName: "List Self Assessment Payments [test only]"
description: This endpoint allows a developer to retrieve a list of payments for a given date range. A unique identifier (National Insurance Number) for the account must be used and a valid date range provided.
(annotations.sandboxData): !include scenarios/listPayments.md
(annotations.scope): "read:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
responses:
  200:
    body:
      application/json:
        type: !include schemas/list_payments_response.json
        examples:
          example-1:
            description:
            value: !include examples/listPayments/retrieve_response.json
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.