is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.clientOrAgentNotAuthorised
  - errors.notFound
displayName: "Retrieve a Self Assessment Balance [test only]"
description: This endpoint allows a developer to retrieve the overall liability broken down into overdue, currently due (payable) and pending (not yet due) amounts. A unique identifier (National Insurance Number) for the account must be used.
(annotations.sandboxData): !include scenarios/retrieveBalance.md
(annotations.scope): "read:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
responses:
  200:
    body:
      application/json:
        type: !include schemas/retrieve_balance_response.json
        examples:
          example-1:
            description: Example response
            value: !include examples/retrieveBalance/retrieve_response.json
          example-2:
            description: Example response where nothing is due
            value: !include examples/retrieveBalance/retrieve_nothing_due.json
          example-3:
            description: Example response where a payment is overdue
            value: !include examples/retrieveBalance/retrieve_overdue.json
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.