is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatTaxYear
  - errors.ruleTaxYearNotSupported
  - errors.ruleTaxYearRangeInvalid
  - errors.formatSource
  - errors.clientOrAgentNotAuthorised
  - errors.codingOutNotFound
  - queryParameters.source
displayName: Retrieve Coding Out Underpayments and Debt Amounts [test only]
description:
    This endpoint enables you to retrieve HMRC-held coding out underpayments and debt amounts or user submitted amended coding out
    amounts for a previous tax year and given National Insurance number.
(annotations.sandboxData): !include scenarios/retrieveCodingOutUnderpayments.md
(annotations.scope): "read:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
responses:
  200:
    body:
      application/json:
        type: !include schemas/retrieve_coding_out_underpayments_response.json
        examples:
          example-1:
            description: Example Response
            value: !include examples/retrieveCodingOutUnderpayments/retrieve_coding_out_underpayments_response.json
    headers:
      X-CorrelationId:
        example: a1e8057e-fbbc-47a8-a8b4-78d9f015c253
        description: Unique ID for operation tracking <br> String, 36 characters.