is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.clientOrAgentNotAuthorised
  - errors.notFound
displayName: "Retrieve a Self Assessment Charge's History [test only]"
description: This endpoint allows a developer to retrieve the history of changes to an individual charge. A unique identifier (National Insurance Number) for the account must be used and a charge identifier provided.
(annotations.sandboxData): !include scenarios/retrieveChargeHistory.md
(annotations.scope): "read:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
responses:
  200:
    body:
      type: !include schemas/retrieve_charge_history_response.json
      examples:
        example-1:
          description:
          value: !include examples/retrieveChargeHistory/retrieve_response.json
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.